allowBuilds:
  esbuild: true
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - astro-git-dates@1.0.1
patchedDependencies:
  astro-d1-search@1.0.0: patches/astro-d1-search@1.0.0.patch
  astro@7.3.5: patches/astro@7.3.5.patch
