name: Twice daily deployment

on:
  push:
  schedule:
    - cron: '0 0/12 * * *' # every 12 hours
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zander-wtf
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
