name: Deploy to Cloudflare

env:
  SUPABASE_USER_ID: ${{ secrets.SUPABASE_USER_ID }}
  OTTER_API_KEY: ${{ secrets.OTTER_API_KEY }}
  LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

on:
  schedule:
    - cron: '0 0/12 * * *' # every 12 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm build
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=zander-wtf
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
